language: objective-c

before_install:
  - brew update
  - brew unlink xctool
  - brew install xctool
  - gem install cocoapods -v 0.29.0 --no-ri --no-doc

script:
  - cd MotioSDK
  - pod install
  - xctool -workspace MotioSDK.xcworkspace -scheme MotioSDK -sdk iphonesimulator build test

notifications:
  email:
    recipients:
      - ios@getmotio.com

branches:
  only:
    - master